/**
 * Terms of Use and Privacy Policy — the single source of truth.
 *
 * WHY THIS IS DATA AND NOT TWO HTML FILES
 *
 * These documents have to exist in two places at once. §9.3 [HARD] requires
 * them at stable public URLs before submission, because App Store Connect
 * fetches the privacy one during review. And they should be readable inside the
 * app without a network round trip, because the alternative is bouncing a user
 * out to Safari to read the terms of the thing they are in the middle of
 * subscribing to — and because a legal document that 404s on a train is a
 * legal document you have not really published.
 *
 * Two copies of a legal text is the kind of duplication that goes wrong
 * quietly: someone corrects the web page, nobody touches the app, and the two
 * disagree for a year. So the text lives here as structured data, the app
 * renders it directly, `npm run legal` generates the web pages from it, and
 * tests/legal.test.ts fails if the generated HTML has drifted from what is
 * committed in web/.
 *
 * ACCURACY NOTE
 *
 * The privacy policy previously declared "anonymous usage and crash data" and
 * named Sentry and PostHog as processors. Both packages are installed and
 * neither is initialised — their keys are unset, so the init functions return
 * immediately (see the comment in core/bootstrap.ts). The app collects no
 * analytics and no crash reports, so the policy said something untrue and
 * contradicted the App Store privacy labels, which is exactly the inconsistency
 * a reviewer checks. Corrected below. If those keys are ever set, this file and
 * the labels have to move in the same release.
 */

export type Block =
  | { kind: 'p'; text: string }
  | { kind: 'list'; items: string[] }
  /** Set off with an accent rule. Used sparingly — it stops meaning anything otherwise. */
  | { kind: 'note'; text: string }
  | { kind: 'rows'; caption: string; rows: { label: string; value: string }[] };

export type Section = { heading: string; blocks: Block[] };

export type LegalDoc = {
  slug: 'terms' | 'privacy';
  title: string;
  updated: string;
  intro: Block[];
  sections: Section[];
};

const CONTACT = 'reckon2026@outlook.com';

const DISCLAIMER =
  'Reckon is not affiliated with, endorsed by, or connected to the Premier ' +
  'League, the Football Association, or any football club. Predictions are ' +
  'statistical estimates, not advice, and should not be used for betting purposes.';

export const TERMS: LegalDoc = {
  slug: 'terms',
  title: 'Terms of Use',
  updated: '16 August 2026',
  intro: [
    { kind: 'p', text: 'These terms apply when you use Reckon. By using the app you accept them.' },
  ],
  sections: [
    {
      heading: 'What Reckon is',
      blocks: [
        {
          kind: 'p',
          text:
            'Reckon is a prediction game. A statistical model publishes probabilities for ' +
            'football matches, you make your own predictions, and each gameweek you are ' +
            'scored against the model.',
        },
        {
          kind: 'note',
          text:
            'Reckon is not a gambling service. There is no wagering of any kind. There is ' +
            'no real or virtual currency, no stakes, no odds from bookmakers, and no links ' +
            'to betting services. Points have no monetary value, cannot be exchanged for ' +
            'anything, and cannot be transferred.',
        },
      ],
    },
    {
      heading: 'Predictions are estimates, not advice',
      blocks: [
        {
          kind: 'p',
          text:
            'The model produces statistical estimates. It is frequently wrong, and the app ' +
            'publishes its accuracy record precisely so you can see how often. Nothing in ' +
            'Reckon is a recommendation, a tip, or advice of any kind, and it must not be ' +
            'relied on for betting or any other financial decision.',
        },
      ],
    },
    {
      heading: 'Your account',
      blocks: [
        {
          kind: 'p',
          text:
            'The app creates an anonymous account on first launch so your predictions are ' +
            'saved. You can sign in with Apple to keep your record across devices, but you ' +
            'are never required to. You can delete your account at any time from Settings.',
        },
        {
          kind: 'p',
          text:
            'Display names are generated by us. You cannot set your own, which is why there ' +
            'is no user-submitted text anywhere in the app.',
        },
      ],
    },
    {
      heading: 'Subscriptions',
      blocks: [
        {
          kind: 'p',
          text:
            'Reckon is free to play. An optional subscription unlocks additional statistical ' +
            'detail. Subscriptions are billed through your Apple ID and renew automatically ' +
            'unless cancelled at least 24 hours before the current period ends.',
        },
        {
          kind: 'p',
          text:
            'Manage or cancel in Settings on your iPhone, under your name, then ' +
            'Subscriptions. We cannot cancel or refund on your behalf — Apple handles ' +
            'billing entirely.',
        },
      ],
    },
    {
      heading: 'Fair play',
      blocks: [
        {
          kind: 'p',
          text:
            'Predictions lock when a match kicks off, enforced by our server clock. Do not ' +
            'attempt to submit or alter predictions after kick-off, operate multiple ' +
            'accounts to game the leaderboard, or access the service by automated means. We ' +
            'may suspend accounts that do.',
        },
      ],
    },
    {
      heading: 'Availability',
      blocks: [
        {
          kind: 'p',
          text:
            'We aim to keep Reckon available and its data current, but we depend on ' +
            'third-party football data and cannot guarantee either. Fixtures, results and ' +
            'predictions may be delayed, incomplete or wrong.',
        },
      ],
    },
    {
      heading: 'Intellectual property',
      blocks: [
        {
          kind: 'p',
          text:
            'The app, its design and the model are ours. Club names are used descriptively ' +
            'to identify matches. The app contains no club crests, badges, kit imagery or ' +
            'competition branding.',
        },
      ],
    },
    {
      heading: 'Liability',
      blocks: [
        {
          kind: 'p',
          text:
            'Reckon is provided as-is, for entertainment. To the extent permitted by law we ' +
            'are not liable for any loss arising from your use of it, or from reliance on ' +
            'any prediction. Nothing here limits liability that cannot be limited by law.',
        },
      ],
    },
    {
      heading: 'Changes',
      blocks: [
        { kind: 'p', text: 'If these terms change materially we will say so in the app before the change takes effect.' },
      ],
    },
    {
      heading: 'Governing law',
      blocks: [
        { kind: 'p', text: 'These terms are governed by the law of England and Wales.' },
      ],
    },
    {
      heading: 'Contact',
      blocks: [{ kind: 'p', text: CONTACT }, { kind: 'note', text: DISCLAIMER }],
    },
  ],
};

export const PRIVACY: LegalDoc = {
  slug: 'privacy',
  title: 'Privacy Policy',
  updated: '16 August 2026',
  intro: [
    {
      kind: 'p',
      text:
        'Reckon is a football prediction game. This policy explains exactly what data the ' +
        'app handles. It is short because the app collects very little — that is a design ' +
        'decision, not an omission.',
    },
  ],
  sections: [
    {
      heading: 'What we collect',
      blocks: [
        {
          kind: 'rows',
          caption: 'All of it is linked to your account, because all of it is your game.',
          rows: [
            { label: 'An account identifier', value: 'To save your predictions and score them' },
            { label: 'A generated display name, e.g. "Quiet Chevron 41"', value: 'To show you on the leaderboard' },
            { label: 'Your predictions, points and streak', value: 'The game itself' },
            { label: 'Subscription status', value: 'To unlock premium features' },
          ],
        },
      ],
    },
    {
      heading: 'What we do not collect',
      blocks: [
        {
          kind: 'list',
          items: [
            'No email address. You can play without giving one.',
            'No real name. Display names are generated by us, not entered by you.',
            'No location data.',
            'No contacts, photos, or health data.',
            'No analytics. We do not record which screens you open or what you tap.',
            'No crash reports.',
            'No advertising identifier (IDFA). We do not track you across other apps or websites, which is why Reckon never shows the "Ask App Not to Track" prompt.',
          ],
        },
        {
          kind: 'note',
          text:
            'An earlier version of this policy mentioned anonymous usage and crash data. ' +
            'Those tools were never switched on, so the app has never sent either, and the ' +
            'wording has been corrected to say so.',
        },
      ],
    },
    {
      heading: 'Accounts',
      blocks: [
        {
          kind: 'p',
          text:
            'You can use Reckon without signing up. The app creates an anonymous account on ' +
            'your device so your predictions are saved. If you choose to sign in with Apple, ' +
            'we receive an identifier from Apple — we do not receive or store your email ' +
            'address or your name.',
        },
        {
          kind: 'note',
          text:
            'If you sign in with Apple and that Apple ID already has a Reckon account, the ' +
            'existing account takes over and any predictions made anonymously on this device ' +
            'are discarded. The app warns you before this happens.',
        },
      ],
    },
    {
      heading: 'Deleting your account',
      blocks: [
        {
          kind: 'p',
          text:
            'You can delete your account at any time from Settings, then Delete account, ' +
            'inside the app. This permanently removes your predictions, points, streak and ' +
            'display name. It cannot be undone, and we do not keep a copy.',
        },
      ],
    },
    {
      heading: 'Who we share data with',
      blocks: [
        { kind: 'p', text: 'We do not sell your data. We use these service providers to run the app:' },
        {
          kind: 'list',
          items: [
            'Supabase — database and accounts, hosted in the EU',
            'RevenueCat — subscription status',
            'Apple — payments, and Sign in with Apple if you use it',
          ],
        },
      ],
    },
    {
      heading: 'Your rights',
      blocks: [
        {
          kind: 'p',
          text:
            'Under UK and EU data protection law you can ask for a copy of your data, ask us ' +
            'to correct it, or ask us to delete it. Deletion is available immediately in the ' +
            'app. For anything else, contact us at the address below and we will respond ' +
            'within 30 days.',
        },
      ],
    },
    {
      heading: 'Children',
      blocks: [
        {
          kind: 'p',
          text:
            'Reckon is not directed at children under 13 and we do not knowingly collect ' +
            'data from them. The app contains no gambling, no wagering and no real-money ' +
            'features of any kind.',
        },
      ],
    },
    {
      heading: 'Changes',
      blocks: [
        { kind: 'p', text: 'If this policy changes materially we will say so in the app before the change takes effect.' },
      ],
    },
    {
      heading: 'Contact',
      blocks: [{ kind: 'p', text: CONTACT }, { kind: 'note', text: DISCLAIMER }],
    },
  ],
};

export const LEGAL_DOCS: Record<'terms' | 'privacy', LegalDoc> = {
  terms: TERMS,
  privacy: PRIVACY,
};
