/**
 * Data access with a dev-fixture fallback.
 *
 * §11 Phase 2 says "all against real data". Until the Supabase project exists,
 * "real" means real *model output* — sample_gameweek.json is generated by
 * `python -m premmodel.jobs.export_sample`, so every probability, score matrix
 * and confidence value here came out of the fitted Dixon-Coles/Elo ensemble,
 * not from someone's imagination.
 *
 * The payload shape is identical to what Supabase returns, so deleting the
 * fixture and setting EXPO_PUBLIC_SUPABASE_URL is the entire migration.
 */

import { z } from 'zod';

import {
  fetchFreePredictions,
  fetchGameweek,
  fetchPremiumPredictions,
} from '@/api/client';
import { currentSeason } from './season';
import sampleGameweek from './sample_gameweek.json';

export const TeamSchema = z.object({
  slug: z.string(),
  name: z.string(),
  short_name: z.string(),
  primary_color: z.string(),
  secondary_color: z.string(),
});

export const PredictionSchema = z.object({
  p_home: z.number().min(0).max(1),
  p_draw: z.number().min(0).max(1),
  p_away: z.number().min(0).max(1),
  exp_home_goals: z.number(),
  exp_away_goals: z.number(),
  p_btts: z.number(),
  p_over_25: z.number(),
  p_home_cs: z.number(),
  p_away_cs: z.number(),
  confidence: z.number(),
  confidence_band: z.string(),
  confidence_reason: z.string(),
  data_regime: z.enum(['prior_heavy', 'blended', 'current']),
  scoreline_matrix: z.array(z.array(z.number())),
  top_scorelines: z.array(
    z.object({ home: z.number(), away: z.number(), p: z.number() }),
  ),
});

/**
 * What a free-tier user gets (§8.1): the model's pick and how sure it is, with
 * no probabilities behind it. Deliberately a separate type from Prediction so
 * the UI cannot accidentally render premium fields that are not there — an
 * unentitled response genuinely does not contain them (§9.2 [HARD]).
 */
export const FreePickSchema = z.object({
  headline_pick: z.enum(['home', 'draw', 'away']),
  confidence: z.number(),
  confidence_band: z.string(),
  confidence_reason: z.string(),
  data_regime: z.enum(['prior_heavy', 'blended', 'current']),
});

export const FixtureSchema = z.object({
  id: z.string(),
  gameweek: z.number(),
  kickoff_utc: z.string(),
  status: z.enum(['scheduled', 'live', 'finished', 'postponed', 'cancelled']),
  home_team: TeamSchema,
  away_team: TeamSchema,
  home_goals: z.number().nullable(),
  away_goals: z.number().nullable(),
  prediction: PredictionSchema.nullable(),
  free_pick: FreePickSchema.nullable().default(null),
});

export const GameweekSchema = z.object({
  season: z.string(),
  gameweek: z.number(),
  generated_at: z.string(),
  model_version: z.string(),
  fixtures: z.array(FixtureSchema),
});

export type Team = z.infer<typeof TeamSchema>;
export type Prediction = z.infer<typeof PredictionSchema>;
export type Fixture = z.infer<typeof FixtureSchema>;
export type Gameweek = z.infer<typeof GameweekSchema>;

const usingLiveBackend = Boolean(process.env.EXPO_PUBLIC_SUPABASE_URL);

export function isUsingSampleData(): boolean {
  return !usingLiveBackend;
}

/** Top-N scorelines, read off the matrix the server already sent. */
function topScorelines(matrix: number[][], k: number) {
  const cells: { home: number; away: number; p: number }[] = [];
  for (let h = 0; h < matrix.length; h++) {
    const row = matrix[h] ?? [];
    for (let a = 0; a < row.length; a++) cells.push({ home: h, away: a, p: row[a] ?? 0 });
  }
  return cells.sort((x, y) => y.p - x.p).slice(0, k);
}

export async function loadGameweek(gameweek: number): Promise<Gameweek> {
  if (usingLiveBackend) {
    const season = currentSeason();
    const fixtures = await fetchGameweek(season, gameweek);
    const ids = fixtures.map((f) => f.id);

    // Ask for both tiers. An unentitled caller gets [] from predictions_premium
    // straight out of the database — not an error, simply no rows — so an empty
    // premium result is the correct signal to fall back to the free pick.
    const [premium, free] = await Promise.all([
      fetchPremiumPredictions(ids),
      fetchFreePredictions(ids),
    ]);

    const premiumById = new Map(premium.map((p) => [p.fixture_id, p]));
    const freeById = new Map(free.map((p) => [p.fixture_id, p]));

    return GameweekSchema.parse({
      season,
      gameweek,
      generated_at: new Date().toISOString(),
      model_version: 'live',
      fixtures: fixtures.map((f) => {
        const full = premiumById.get(f.id);
        const pick = freeById.get(f.id);
        return {
          ...f,
          prediction: full
            ? { ...full, top_scorelines: topScorelines(full.scoreline_matrix, 5) }
            : null,
          free_pick: pick
            ? {
                headline_pick: pick.headline_pick,
                confidence: pick.confidence,
                confidence_band: pick.confidence_band,
                confidence_reason: pick.confidence_reason,
                data_regime: pick.data_regime,
              }
            : null,
        };
      }),
    });
  }

  // Validated even though it is a local file: it is generated by a separate
  // program, and a silent shape drift between the Python exporter and this
  // client is exactly the bug that would waste an afternoon.
  return GameweekSchema.parse(sampleGameweek);
}

export async function loadFixture(id: string): Promise<Fixture | undefined> {
  const week = await loadGameweek(1);
  return week.fixtures.find((f) => f.id === id);
}

/** §5.6: probabilistic, never assertive. No "will win" anywhere. */
export function headlinePick(p: Prediction, home: Team, away: Team): string {
  const max = Math.max(p.p_home, p.p_draw, p.p_away);
  if (max === p.p_home) return home.short_name;
  if (max === p.p_away) return away.short_name;
  return 'Draw';
}

export function formatKickoff(iso: string): string {
  return new Date(iso).toLocaleString('en-GB', {
    weekday: 'short',
    day: 'numeric',
    month: 'short',
    hour: '2-digit',
    minute: '2-digit',
  });
}
